databases:
  - name: _home
    databaseName: _home
    user: _home

services:
  - type: web
    name: _home
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn _home.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: _home
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
